#!/bin/sh

case "$1" in

installer)

# we should have d-i downloaded by now.
# partman comes in a udeb from the network so we have to hook here
# and replace the partman-base.postinst file
sed -i 's/partman/\/tmp\/early_command partman/' /var/lib/dpkg/info/partman-base.postinst
logger early_command modified partman-base.postinst
;;

partman)

# do filesystem stuff: detect our config, fdisk, lvm, raid, mount /target
logger server-farm.early_command partition configuration starting


# Downloading parted, partprobe, and necessary libraries
mkdir /tmp/setup
cd /tmp/setup
wget http://192.168.22.101/setup.tar
tar xf setup.tar
export PATH=$PATH:/tmp/setup
export LD_LIBRARY_PATH=/tmp/setup/lib

# Stop all arrays
for i in `cat /proc/mdstat | grep ^md | cut -d" " -f1`
do
    mdadm --stop --force /dev/$i
done

# Cleaning partitions
# Wiping software raid superblock
for i in sda sdb sdc sdd
do
mdadm --zero-superblock  /dev/${i}1
mdadm --zero-superblock  /dev/${i}2
mdadm --zero-superblock  /dev/${i}5
done

# blank the drives table of contents
for i in sda sdb sdc sdd
do
   dd if=/dev/zero of=$i bs=446 count=1
done

# Using parted to reset the partition table to MSDOS style on all thre hard drives
parted --script /dev/sda mklabel gpt
parted --script /dev/sdb mklabel gpt
parted --script /dev/sdc mklabel gpt
parted --script /dev/sdd mklabel gpt
parted --script /dev/sde mklabel gpt
parted --script /dev/sdf mklabel gpt
parted --script /dev/sda mklabel msdos
parted --script /dev/sdb mklabel msdos
parted --script /dev/sdc mklabel msdos
parted --script /dev/sdd mklabel msdos
parted --script /dev/sde mklabel msdos
parted --script /dev/sdf mklabel msdos

# Partition info:
# sda1 /boot 512mb (raid autodetect)
# sda2 swap 20G (raid autodetect)
# sda5 / rest (raid autodetect)
# Sending commands that are normally interactive to fdisk
for i in sda sdb sdc sdd sde sdf
do
echo "
n
p
1

+300M
a
1
n
p
2

+20480M
n
e



n
l


t
1
fd
t
2
fd
t
5
fd
w
" | fdisk /dev/$i
done

# Using partprobe to re-read partition table of all three hard drives
partprobe -s /dev/sda
partprobe -s /dev/sdb
partprobe -s /dev/sdc
partprobe -s /dev/sdd

# Loading raid modules
modprobe raid1
modprobe raid0
modprobe raid10

# Creating /boot raid1
echo y | mdadm -C /dev/md0 -n 2 -l raid1 --metadata=0.90 /dev/sda1 /dev/sdb1

# Creating spare raid1
echo y | mdadm -C /dev/md1 -n 2 -l raid1 --metadata=default /dev/sda2 /dev/sdb2

# Creating / raid10
echo y | mdadm -C /dev/md2 -n 6 -l raid10 /dev/sda5 /dev/sdb5 /dev/sdc5 /dev/sdd5 /dev/sde5 /dev/sdf5

# Creating swap
echo y | mdadm -C /dev/md3 -n 2 -l raid1 --metadata=default /dev/sdc2 /dev/sdd2

# Formatting /boot
mkfs.ext4 /dev/md0

# Formatting /
mkfs.ext4 /dev/md1

# Formatting /dev/md2
mkfs.ext4 /dev/md2

# Formatting swap
mkswap /dev/md3

# Mounting filesystems
mkdir /target
mount /dev/md2 /target -t ext4
mkdir /target/boot
mount /dev/md0 /target/boot -t ext4

# Creating fstab
mkdir /target/etc
echo \# /etc/fstab: static file system information. > /target/etc/fstab
echo \# >> /target/etc/fstab
echo proc                /proc           proc    nodev,noexec,nosuid 0 0 >> /target/etc/fstab
echo /dev/md2            /               ext4    errors=remount-ro   0 1 >> /target/etc/fstab
echo /dev/md0            /boot           ext4    defaults            1 2 >> /target/etc/fstab
echo /dev/md3            none            swap    sw                  0 0 >> /target/etc/fstab

 ;;

*)

  echo $0: This script is destructive and should only be run as part of the debian-installer process ;;esac
