#!/bin/sh

case "$1" in

installer)

# we should have d-i downloaded by now.
# partman comes in a udeb from the network so we have to hook here
# and replace the partman-base.postinst file
sed -i 's/partman/\/tmp\/early_command partman/' /var/lib/dpkg/info/partman-base.postinst
logger early_command modified partman-base.postinst
;;

partman)

# do filesystem stuff: detect our config, fdisk, lvm, raid, mount /target
logger server-farm.early_command partition configuration starting


# Downloading parted, partprobe, and necessary libraries
mkdir /tmp/setup
cd /tmp/setup
wget http://192.168.4.235/setup.tar
tar xf setup.tar
export PATH=$PATH:/tmp/setup
export LD_LIBRARY_PATH=/tmp/setup/lib

# Stop all arrays
for i in `cat /proc/mdstat | grep ^md | cut -d" " -f1`
do
    mdadm --stop --force /dev/$i
done

# Cleaning partitions 
# Wiping software raid superblock
for i in sda sdb 
do
mdadm --zero-superblock  /dev/${i}1
mdadm --zero-superblock  /dev/${i}2
mdadm --zero-superblock  /dev/${i}5
done

# Clear partition table
for i in sda sdb
do
    dd if=/dev/zero of=/dev/$i bs=446 count=1
done

# Using parted to reset the partition table to MSDOS style on all thre hard drives
parted --script /dev/sda mklabel gpt
parted --script /dev/sdb mklabel gpt
parted --script /dev/sdc mklabel gpt
parted --script /dev/sdd mklabel gpt
parted --script /dev/sde mklabel gpt
parted --script /dev/sdf mklabel gpt
parted --script /dev/sda mklabel msdos
parted --script /dev/sdb mklabel msdos
parted --script /dev/sdc mklabel msdos
parted --script /dev/sdd mklabel msdos
parted --script /dev/sde mklabel msdos
parted --script /dev/sdf mklabel msdos

# Partition info:
# sda1 /boot 512mb (raid autodetect)
# sda2 swap 20G (raid autodetect)
# sda5 / 20G (raid autodetect)
# sda6 swift rest
# Sending commands that are normally interactive to fdisk
for i in sda sdb 
do
echo "
n
p
1

+512M
a
1
n
p
2

+20480M
n
e



n
l

+20480M
n
l


t
1
fd
t
2
fd
t
5
fd
t
6
83
w
" | fdisk /dev/$i
done

# Using partprobe to re-read partition table of all three hard drives
partprobe -s /dev/sda
partprobe -s /dev/sdb

# Loading raid modules
modprobe raid1
modprobe raid0
modprobe raid10

# Creating /boot raid1
echo y | mdadm -C /dev/md0 -n 2 -l raid1 --metadata=0.90 /dev/sda1 /dev/sdb1

# Creating / raid1
echo y | mdadm -C /dev/md1 -n 2 -l raid1 --metadata=default /dev/sda2 /dev/sdb2 

# Creating swap
echo y | mdadm -C /dev/md2 -n 2 -l raid1 --metadata=default /dev/sda5 /dev/sdb5

# Formatting /boot
mkfs.ext4 -F /dev/md0

# Formatting /
mkfs.ext4 -F /dev/md1

# Formatting swap
mkswap /dev/md2

# Format swift drives
mkfs.xfs -f /dev/sda6
mkfs.xfs -f /dev/sdb6
mkfs.xfs -f /dev/sdc
mkfs.xfs -f /dev/sdd
mkfs.xfs -f /dev/sde
mkfs.xfs -f /dev/sdf

# Mounting filesystems
mkdir /target
mount /dev/md1 /target -t ext4
mkdir /target/boot
mount /dev/md0 /target/boot -t ext4

# Make swift mount points
mkdir -p /target/srv/node
mkdir /target/srv/node/sda6
mkdir /target/srv/node/sdb6
mkdir /target/srv/node/sdc
mkdir /target/srv/node/sdd
mkdir /target/srv/node/sde
mkdir /target/srv/node/sdf

# Creating fstab
mkdir /target/etc
echo \# /etc/fstab: static file system information. > /target/etc/fstab
echo \# >> /target/etc/fstab
echo proc                /proc           proc    nodev,noexec,nosuid 0 0 >> /target/etc/fstab
echo /dev/md0            /boot           ext4    defaults            1 2 >> /target/etc/fstab
echo /dev/md1            /               ext4    errors=remount-ro   0 1 >> /target/etc/fstab
echo /dev/md2            none            swap    sw                  0 0 >> /target/etc/fstab
echo /dev/sda6           /srv/node/sda6  xfs     noatime,nodiratime,nobarrier,logbufs=8 0 0 >> /target/etc/fstab
echo /dev/sdb6           /srv/node/sdb6  xfs     noatime,nodiratime,nobarrier,logbufs=8 0 0 >> /target/etc/fstab
echo /dev/sdc           /srv/node/sdc  xfs     noatime,nodiratime,nobarrier,logbufs=8 0 0 >> /target/etc/fstab
echo /dev/sdd           /srv/node/sdd  xfs     noatime,nodiratime,nobarrier,logbufs=8 0 0 >> /target/etc/fstab
echo /dev/sde           /srv/node/sde  xfs     noatime,nodiratime,nobarrier,logbufs=8 0 0 >> /target/etc/fstab
echo /dev/sdf           /srv/node/sdf  xfs     noatime,nodiratime,nobarrier,logbufs=8 0 0 >> /target/etc/fstab

 ;;

*)

  echo $0: This script is destructive and should only be run as part of the debian-installer process ;;esac
