#!/bin/sh

case "$1" in

installer)

# we should have d-i downloaded by now.
# partman comes in a udeb from the network so we have to hook here
# and replace the partman-base.postinst file
sed -i 's/partman/\/tmp\/early_command partman/' /var/lib/dpkg/info/partman-base.postinst
logger early_command modified partman-base.postinst
;;

partman)

# do filesystem stuff: detect our config, fdisk, lvm, raid, mount /target
logger server-farm.early_command partition configuration starting


# Downloading parted, partprobe, and necessary libraries
mkdir /tmp/setup
cd /tmp/setup
wget http://192.168.255.1/setup.tar
tar xf setup.tar
export PATH=$PATH:/tmp/setup
export LD_LIBRARY_PATH=/tmp/setup/lib

# Using parted to reset the partition table to MSDOS style on all thre hard drives
parted --script /dev/sda mklabel gpt
parted --script /dev/sdb mklabel gpt
#parted --script /dev/sdc mklabel gpt
parted --script /dev/sda mklabel msdos
parted --script /dev/sdb mklabel msdos
#parted --script /dev/sdc mklabel msdos

# Partition info:
# sda1 /boot 512mb (raid autodetect)
# sda2 swap 1024 (raid autodetect)
# sda3 / rest (raid autodetect)
# Sending commands that are normally interactive to fdisk
for i in sda sdb
do
echo "
n
p
1

+512M
a
1
n
p
2

+1024M
n
p
3


t
1
fd
t
2
82
t
3
fd
w
" | fdisk /dev/$i
done

# Using partprobe to re-read partition table of all three hard drives
partprobe /dev/sda
partprobe /dev/sdb
#partprobe /dev/sdc

# Loading raid1 module
modprobe raid1

# Cleaning partitions of lvm
dd if=/dev/zero of=/dev/sda1 bs=1M count=10
dd if=/dev/zero of=/dev/sdb1 bs=1M count=10

# Wiping software raid superblock
mdadm --zero-superblock /dev/sda1
mdadm --zero-superblock /dev/sdb1

# Creating /boot raid1
mdadm -C /dev/md0 -n 2 -l raid1 --metadata=0.90 /dev/sda1 /dev/sdb1

# Cleaning partitions of lvm
dd if=/dev/zero of=/dev/sda2 bs=1M count=10
dd if=/dev/zero of=/dev/sdb2 bs=1M count=10
dd if=/dev/zero of=/dev/sda3 bs=1M count=10
dd if=/dev/zero of=/dev/sdb3 bs=1M count=10

# Wiping software raid superblock
mdadm --zero-superblock /dev/sda3
mdadm --zero-superblock /dev/sdb3

# Creating / raid1
mdadm -C /dev/md1 -n 2 -l raid1 --metadata=0.90 /dev/sda3 /dev/sdb3

# Formatting /boot
mkfs.ext4 /dev/md0

# Formatting /
mkfs.ext4 /dev/md1

# Formatting swap
mkswap /dev/sda2

# Mounting filesystems
mkdir /target
mount /dev/md1 /target -t ext4
mkdir /target/boot
mount /dev/md0 /target/boot -t ext4

# Creating fstab
mkdir /target/etc
echo \# /etc/fstab: static file system information. > /target/etc/fstab
echo \# >> /target/etc/fstab
echo proc                /proc           proc    nodev,noexec,nosuid 0 0 >> /target/etc/fstab
echo /dev/md1            /               ext4    errors=remount-ro   0 1 >> /target/etc/fstab
echo /dev/md0            /boot           ext4    defaults            1 2 >> /target/etc/fstab
echo /dev/sda2           none            swap    sw                  0 0 >> /target/etc/fstab

 ;;

*)

  echo $0: This script is destructive and should only be run as part of the debian-installer process ;;esac
